DROP TABLE IF EXISTS dan_user;

CREATE TABLE IF NOT EXISTS dan_user (
  id BIGINT PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

